baseurl: /starter
permalink: pretty
markdown: rdiscount
prose:
  rooturl: ''
  siteurl: 'http://prose.github.io/starter/'
  relativeLinks: 'http://prose.github.io/starter/links.jsonp'
  media: 'media'
  metadata:
    "_posts":
      - name: "published"
        field:
          element: "checkbox"
          label: "Published"
          help: "Checkbox help"
          value: false
